-- MySQL Script generated by MySQL Workbench
-- ter 12 mai 2020 13:33:47 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecommerce` ;

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Ecommerce`.`Administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Administradores` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Administradores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` CHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idCategoria` INT(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `preco` DECIMAL(8,2) NULL DEFAULT NULL,
  `estoque` INT(11) NULL DEFAULT NULL,
  `imagens` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Produtos_Categorias1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_Produtos_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Ecommerce`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  `senha` CHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Avaliacoes` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Avaliacoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `idProduto` INT(11) NOT NULL,
  `comentario` VARCHAR(45) NULL DEFAULT NULL,
  `nota` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Avaliacoes_Usuarios_idx` (`idUsuario` ASC),
  INDEX `fk_Avaliacoes_Produtos1_idx` (`idProduto` ASC),
  CONSTRAINT `Produto_idProduto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `Ecommerce`.`Produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Ecommerce`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Carrinho` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Carrinho` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Carrinho_Usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Carrinho_Usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Ecommerce`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`Pedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `status_pedido` TINYINT(4) NOT NULL DEFAULT '0',
  `meio_pagamento` VARCHAR(45) NOT NULL DEFAULT 'default',
  `idPagamento` VARCHAR(45) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Pedido_Usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Ecommerce`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ecommerce`.`itemPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ecommerce`.`itemPedido` ;

CREATE TABLE IF NOT EXISTS `Ecommerce`.`itemPedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idPedido` INT(11) NOT NULL,
  `idProduto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itemPedido_Pedido1_idx` (`idPedido` ASC),
  CONSTRAINT `fk_itemPedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Ecommerce`.`Pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
